### ISSUE TITLE
doubt regarding mitm.py 0ops 2015 web250 forward.

### ISSUE THREAD

**Issue by vaidhyesh1** [x64x6a/ctf-writeups#1]
i ran the code(changed the ip since the question im solving is similar).But Im not sure on the lhost and the host ip to be sent along with the http post method.Thanks.

**Comment by x64x6a** [comment]
The IP in the POST is the public IP of the server that's running the script.
It allows the remove server to connect to the script's host on port 3306.

**Comment by vaidhyesh1** [comment]
Thanks! It helped me a lot!
